# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  #adapter: sqlite3
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  #pool: 5
  #timeout: 5000
  ###adapter: postgresql
  ###encoding: Unicode
  ###username: postgres
  ###password: password
  ###host: localhost
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # next three lines have been added in manually following the 
  # instructions in http://blog.thefirehoseproject.com/posts/setting-up-a-cloud9-development-environment/ 
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: db/development

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: db/test

staging:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  
production:
  ###<<: *default
  ###database: db/production
  url: <%= ENV['DATABASE_URL'] %>

prodcbr:
  <<: *default
  database: prodcbr
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: frozen-beach-84686.csf4r3cevrgb.ap-southeast-2.rds.amazonaws.com
  port: 5432

prodsyd:
  <<: *default
  database: prodsyd
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: frozen-beach-84686.csf4r3cevrgb.ap-southeast-2.rds.amazonaws.com
  port: 5432

